create table CLIENT_MASTER(CLIENTNO VARCHAR(6) PRIMARY KEY,NAME VARCHAR(20) NOT NULL,ADDRESS1 VARCHAR(30),
ADDRESS  VARCHAR(30), CITY VARCHAR(15),
PINCODE NUMERIC, STATE VARCHAR(15), BALDUE NUMERIC)
INSERT INTO CLIENT_MASTER(ClientNo,Name,City,Pincode,State,BalDue) VALUES('C00001','Ivan Bayross','Mumbai',400054,'Maharashtra',15000)
INSERT INTO CLIENT_MASTER(ClientNo,Name,City,Pincode,State,BalDue) VALUES('C00002','Abdul','Newyork',477778,'Pune',12000),('C00003','Immanuel','Abudabi',355558,'Chennai',13000);
select * from CLIENT_MASTER;

CREATE TABLE PRODUCT_MASTER(PRODUCTNO VARCHAR(6) PRIMARY KEY,DESCRIPTION VARCHAR(15) NOT NULL, PROFITPERC NUMERIC NOT NULL,
UNITMEASURE VARCHAR(10) NOT NULL,QTYONHAND NUMERIC NOT NULL,REORDERLVL NUMERIC NOT NULL,SELLPRICE NUMERIC NOT NULL,
COSTPRICE NUMERIC NOT NULL)
INSERT INTO product_master values('P00001','T-Shirts',5,'Piece',200,50,350,250)
INSERT INTO product_master values('P00002','Jeans',6,'Inch',300,60,380,680)
select * from PRODUCT_MASTER;

CREATE TABLE SALESMAN_MASTER(SALESMANNO VARCHAR(6) PRIMARY KEY,SALESMANNAME VARCHAR(20) NOT NULL,ADDRESS1 VARCHAR(30) NOT NULL,
ADDRESS2 VARCHAR(30),CITY VARCHAR(20),PINCODE NUMERIC,State varchar(20),SALAMT NUMERIC NOT NULL,TGTTOGET NUMERIC NOT NULL,
YGTTOGET NUMERIC NOT NULL,YTDSALES NUMERIC NOT NULL,REMARKS VARCHAR(60))
INSERT INTO SALESMAN_MASTER VALUES('S00001','Aman','A/14','Worli','Mumbai','400002','Maharashtra',3000,100,35,50,'Good'),
('S00002','LAMAN','B/14','CURLI','PUNE','500002','Madhyapradesh',4000,200,60,67,'Bad');

create table SALES_ORDER(ORDERNO VARCHAR(6) PRIMARY KEY,CLIENTNO VARCHAR(6),ORDERDATE DATE,
DELYADDR VARCHAR(25),SALESMANNO VARCHAR(6),DELYTYPE  CHAR(1)  CHECK(DELYTYPE LIKE' %P%' OR DELYTYPE LIKE '%F%'),
BILLEDYN CHAR(1)CHECK(BILLEDYN LIKE '%Y%' OR BILLEDYN LIKE '%N%' ),DELYDATE DATE,
ORDERSTATUS VARCHAR(10) CHECK(ORDERSTATUS ='IN PROCESS' OR ORDERSTATUS ='Fulfilled' OR ORDERSTATUS ='Backorder' OR ORDERSTATUS = 'Cancelled'),
foreign key (CLIENTNO)REFERENCES Client_Master(CLIENTNO),foreign key (SALESMANNO)REFERENCES SALESMAN_MASTER(SALESMANNO));
INSERT INTO SALES_ORDER(ORDERNO,ORDERDATE,CLIENTNO,DELYTYPE,BILLEDYN,SALESMANNO,DELYDATE,ORDERSTATUS)
values('O19001','12-june-12','C00001','F','N','S00001','20-july-02','In process');
SELECT * FROM SALES_ORDER;

create table SALES_ORDER_DETAILS(ORDERNO VARCHAR(6),PRODUCTNO VARCHAR(6),QTYORDERED NUMERIC(8),
QTYDISP NUMERIC(8),PRODUCTRATE NUMERIC(10,2),FOREIGN KEY(ORDERNO)REFERENCES SALES_ORDER(ORDERNO),
FOREIGN KEY(PRODUCTNO)REFERENCES PRODUCT_MASTER(PRODUCTNO));
insert into SALES_ORDER_DETAILS(ORDERNO,PRODUCTNO,QTYORDERED,QTYDISP,PRODUCTRATE)values('O19001','P00001',4,4,525);
SELECT * FROM SALES_ORDER_DETAILS;

select NAME FROM CLIENT_MASTER;
SELECT * FROM CLIENT_MASTER WHERE CITY='Mumbai';
select * from PRODUCT_MASTER WHERE SELLPRICE>2000 AND SELLPRICE<5000;
select Name,City,State FROM CLIENT_MASTER WHERE STATE != 'Maharashtra';
select * FROM CLIENT_MASTER WHERE ClientNo = 'C00001' OR ClientNo = 'C00002';
update PRODUCT_MASTER
SET SELLPRICE=1150 WHERE SELLPRICE=350;
SELECT * FROM PRODUCT_MASTER;
DELETE FROM CLIENT_MASTER WHERE CLIENTNO='C0005';
SELECT * FROM CLIENT_MASTER WHERE CITY LIKE '_u%';
select count(*) from PRODUCT_MASTER where SELLPRICE>=1000;


alter table CLIENT_MASTER ADD PHONE_NO NUMERIC;
SELECT * FROM CLIENT_MASTER;
ALTER TABLE CLIENT_MASTER
ALTER COLUMN NAME VARCHAR(60) NOT NULL;
SELECT * FROM CLIENT_MASTER;
ALTER TABLE CLIENT_MASTER
DROP COLUMN Pincode;

-----Joins










